/// Flutter icons FasenateIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FasenateIcons
///      fonts:
///       - asset: fonts/FasenateIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class FasenateIcons {
  FasenateIcons._();

  static const _kFontFam = 'FasenateIcons';
  static const _kFontPkg = null;

  static const IconData communications__2_ = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mark__2_ = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData communications = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData social_media_1 = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData video = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
